version: "3"

services:
  mac-movies-db:
    image: "postgres:latest"
    environment:
      - DATABASE_HOSE=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSEORD=docker
    ports:
      - 5432:5432
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
  server:
    container_name: mac-movies-backend
    image: mac-movies-backend
    build: ./server
    ports:
      - 8080:8080
    networks:
      - my_network
    depends_on:
      - db
  frontend:
    container_name: mac-movies-frontend
    image: mac-movies-frontend
    build: ./client
    ports:
      - 3000:3000
    networks:
      - my_network
    depends_on:
      - db
networks:
  my_network:
    driver: bridge
